export {default as logo} from './logo.png'
export {default as instagram} from './instagram.webp'
export {default as linkedin} from './linkedin.jpeg'
export {default as twitter} from './Twitter.jpeg'
export {default as facebook} from './facebook .jpeg'
export {default as search} from './search.png'
export {default as homeimg} from './homeimg.jpg'
export {default as phone} from './phone.jpeg'
export {default as console} from './console.jpeg'
export {default as laptop} from './laptop.gif'
export {default as camera} from './camera.jpeg'
